[tool.black]
target-version = ["py313"]
include = '(\.pyi?|\.ipynb)$'
extend-exclude = '''
/(
    \.git
  | .*/static
  | .*/media
  | .*/migrations
)/
'''

[tool.isort]
profile = "black"
py_version = 313
multi_line_output = 3
include_trailing_comma = true
skip = ["migrations"]
known_local_folder = ["app_auth", "app_doculess"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "LOCALFOLDER"]
